version: '3.8'

services:
  factorio:
    image: 'factorio:1.1.107'
    volumes:
      - type: bind
        source: ./scenarios/default_lab_scenario
        target: /opt/factorio/scenarios/default_lab_scenario
    ports:
      - '34198:34197/udp'
      - '27015:27015/tcp'
    restart: unless-stopped
    entrypoint: [ "bash", "/scenario.sh", "default_lab_scenario" ]
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512m